#!/bin/bash

cd aom

rm -rf out
mkdir out
cd out

export LIBS="-lc"


if [ $CPU == "arm" ];
then
  CFG="-DARCH_ARM=1 -DENABLE_NEON=0"
fi

if [ $CPU == "x86" ];
then
  CFG="-DARCH_X86=1 -DENABLE_AVX2=0 -DENABLE_SSE4_2=0 -DENABLE_SSE4_1=0 -DENABLE_SSE3=0 -DENABLE_SSE2=0"
fi

if [ $CPU == "arm64" ];
then
  CFG="-DARCH_ARM=1 -DHAVE_NEON=1"
fi

if [ $CPU == "x86_64" ];
then
  CFG="-DARCH_X86_64=1 -DENABLE_AVX2=0"
fi

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_SYSROOT=$SYSROOT  -DCMAKE_C_FLAGS="$CFLAGS $LIBS -Wimplicit-function-declaration" -DCMAKE_CXX_FLAGS="$CFLAGS $LIBS" -DCMAKE_ASM_FLAGS="$CMAKE_ASM_FLAGS" $CFG \
  -DCMAKE_SYSTEM_NAME=Android \
  -DCONFIG_RUNTIME_CPU_DETECT=0 -DAOM_TARGET_CPU=$CPU -DCONFIG_GCC=1 -DCONFIG_PIC=1 \
  -DCMAKE_SYSTEM_VERSION=$API \
  -DCMAKE_ANDROID_NDK=$NDK \
  -DCMAKE_C_LINK_EXECUTABLE=$LD \
  -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
  -DCMAKE_FIND_ROOT_PATH=$PLATFORM \
  -DBUILD_SHARED_LIBS=0 -DENABLE_DOCS=0 -DENABLE_EXAMPLES=0 -DENABLE_TOOLS=0 -DENABLE_TESTS=0 \
   .. 
   make -j6 && make install
   