#!/bin/bash

CPU=${1}

./make pthread $CPU
./make fdk-aac $CPU
./make opencore-amr $CPU
./make vo-amrwbenc $CPU
./make libogg $CPU
./make x265 $CPU
./make x264 $CPU
./make libpng $CPU
./make freetype $CPU
./make fribidi $CPU
./make libass $CPU
./make libuuid $CPU
./make libxml2 $CPU
./make fontconfig $CPU
./make xvidcore $CPU
./make libvpx $CPU
./make lame $CPU
./make vorbis $CPU
./make theora $CPU
./make opus $CPU
./make openssl $CPU
./make librtmp $CPU
./make speex $CPU
./make libsoxr $CPU
./make wavpack $CPU
./make xavc $CPU
./make xavc2 $CPU
./make libwebp $CPU
./make ffmpeg $CPU