#!/bin/bash

cd openjpeg

rm -r out
mkdir out
cd out

make clean

export LIBS=""

# for arm remove pixel_avg_pp calc_Residual ssd_s  chroma add_ps

CCMF=$(pwd)/crosscompile.cmake

echo \
"set(CROSS_COMPILE_ARM $CROSS_COMPILE_ARM)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER $CC)
set(CMAKE_CXX_COMPILER \"$CXX\")
set(CMAKE_C_LINK_EXECUTABLE $LD)
set(CMAKE_CXX_LINK_EXECUTABLE $LD)
set(CMAKE_CXX_LINK_EXECUTABLE $LD)
set(CMAKE_ASM_COMPILER $ASM)
set(CMAKE_FIND_ROOT_PATH $PLATFORM)
et(CMAKE_SYSROOT $SYSROOT)" > $CCMF

#-DCMAKE_TOOLCHAIN_FILE=$CCM

cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_SYSROOT=$SYSROOT  -DCMAKE_C_FLAGS="$CFLAGS $LIBS" -DCMAKE_CXX_FLAGS="$CFLAGS $LIBS" -DCMAKE_ASM_FLAGS="$CMAKE_ASM_FLAGS" \
  -DCMAKE_SYSTEM_NAME=Android \
  -DCMAKE_SYSTEM_VERSION=$API \
  -DCMAKE_ANDROID_ABI=$SO_ARCH \
  -DCMAKE_ANDROID_NDK=$NDK \
  -DCMAKE_C_LINK_EXECUTABLE=$LD \
  -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
  -DCMAKE_FIND_ROOT_PATH=$PLATFORM \
  -DANDROID_PIE=ON \
       -DENABLE_SHARED=OFF \
       -DCROSS_COMPILE_ARM=$CROSS_COMPILE_ARM \
   .. && make VERBOSE=1 -j8 && make install
#ccmake ../source 
   