#!/bin/bash

cd x265

CCMF=$(pwd)/crosscompile.cmake

echo \
"set(CMAKE_C_COMPILER $CC)
set(CMAKE_CXX_COMPILER \"$CXX\")
set(CMAKE_C_LINK_EXECUTABLE $LD)
set(CMAKE_CXX_LINK_EXECUTABLE $LD)
set(CMAKE_EXE_LINKER_FLAGS \"$LDFLAGS\")
set(CMAKE_ASM_COMPILER $AS)
set(CMAKE_FIND_ROOT_PATH $PLATFORM)
et(CMAKE_SYSROOT $SYSROOT)" > $CCMF

rm -r out
mkdir out
cd out

make clean

export LIBS="-lc"


cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_SYSROOT=$SYSROOT -DCMAKE_TOOLCHAIN_FILE=$CCM -DCMAKE_C_FLAGS="$CFLAGS $LIBS" \
  -DCMAKE_SYSTEM_NAME=Android \
  -DCMAKE_SYSTEM_VERSION=$API \
  -DCMAKE_ANDROID_ABI=$SO_ARCH \
  -DCMAKE_ANDROID_NDK=$NDK \
  -DCMAKE_C_LINK_EXECUTABLE=$LD \
  -DCMAKE_FIND_ROOT_PATH=$PLATFORM \
  -DANDROID_PIE=ON \
        -DENABLE_SHARED=OFF \
       -DENABLE_ASSEMBLY=OFF \
       -DENABLE_CLI=OFF \
       -DENABLE_LIBNUMA=OFF \
       -DENABLE_PIC=ON \
       -DCMAKE_C_LINK_EXECUTABLE=$LD \
   ../source && make V=1 -j8 && make install

   